#!/bin/bash -e
# bootstrap for macOS

check_cmd() {
    command -v "$1" > /dev/null 2>&1
}

need_cmd() {
    if ! check_cmd "$1"; then
        err "command '$1' not found"
    fi
}

msg() {
    printf 'bootstrap: %s\n' "$1"
}

err() {
    msg "$1" >&2
    exit 1
}

macos() {
  check_cmd nix || {
    msg "installing Nix using Determinate Systems installer"
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
  }

  profile_sh=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  [ -f $profile_sh ] && source $profile_sh

  need_cmd nix

  msg "bootstrap completed"

  # will be replaced by generated flake versions
  msg "moving /etc/nix/nix.conf (will be replaced)"
  [ -f /etc/nix/nix.conf ] && sudo mv -f /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
  msg "moving /etc/shells (will be replaced)"
  [ -f /etc/shells ] && sudo mv -f /etc/shells /etc/shells.before-nix-darwin

  ./rebuild
}

if [ "$(uname)" == "Darwin" ]; then
  macos $@
else
  echo "Unsupported operating system: $(uname)"
fi 
