#!/usr/bin/env bash

export NIXPKGS_ALLOW_UNFREE=1
export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
unset CDPATH
FLAKE_DIR=$(cd "$(dirname "$0")"; pwd)

macos() {
  host="$(hostname)"
  FLAKE="${FLAKE:-$host}"
  system="darwinConfigurations.$FLAKE.system"

  echo "rebuilding: on macOS"
  nix --experimental-features 'nix-command flakes' build "${FLAKE_DIR}#$system" --impure $@
  ./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE --impure $@
  rm -rf ./result
}

nixos() {
  host="$(hostname)"
  FLAKE="${FLAKE:-$host}"
  system="nixosConfigurations.$FLAKE.system"

  echo "rebuilding: on NixOS"
  sudo -E /run/current-system/sw/bin/nixos-rebuild switch --flake "${FLAKE_DIR}#$FLAKE" --impure $@
}

wsl() {
  host="$(hostname)"
  FLAKE="${FLAKE:-${host}-wsl}"
  system="nixosConfigurations.$FLAKE.system"

  echo "rebuilding: on WSL"
  /run/wrappers/bin/sudo -E /run/current-system/sw/bin/nixos-rebuild switch --flake "${FLAKE_DIR}#$FLAKE" --impure $@
}

if [ "$(uname)" == "Darwin" ]; then
  macos $@
elif [[ $(grep -i microsoft /proc/version) ]]; then
  wsl $@
elif [ "$(uname)" == "Linux" ]; then
  nixos $@
else
  echo "Unsupported operating system"
fi
