-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';

-- boilerplate

local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end

local is_linux = function()
	return wezterm.target_triple:find("linux") ~= nil
end

local is_macos = function()
	return wezterm.target_triple:find("darwin") ~= nil
end

local scheme_name_for_appearance = function(appearance)
  if appearance:find 'Dark' then
    return 'OneDark (base16)'
  end
  return 'One Light (base16)'
end

local get_window_decorations = function()
  if is_macos() then
    return 'INTEGRATED_BUTTONS|RESIZE'
  else
    return 'RESIZE'
  end
end

local get_window_padding = function()
  if is_macos() then
    return {
      left = 15,
      right = 15,
      top = 50,
      bottom = 10,
    }
  else
    return {
      left = 15,
      right = 15,
      top = 10,
      bottom = 10,
    }
  end
end

local get_font_size = function()
  if is_linux() then
    return 11.0
  end
  return 14.0
end

-- fonts

config.font = wezterm.font("IosevkaLB", {weight="DemiBold"})
config.font_size = get_font_size()
config.font_rules = {
  {
    intensity = "Bold",
    font = wezterm.font("IosevkaLB", {weight="Bold"})
  }
}
config.harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' }
config.initial_cols = 110
config.initial_rows = 35

-- window configuration
config.window_decorations = get_window_decorations()
config.window_padding = get_window_padding()

-- colors
local appearance = wezterm.gui.get_appearance()
local scheme_name = scheme_name_for_appearance(appearance)
local scheme = wezterm.get_builtin_color_schemes()[scheme_name]
config.color_scheme = scheme_name

-- environment variables
config.set_environment_variables = {
  terminal_appearance = appearance:lower()
}

-- tab bar
config.hide_tab_bar_if_only_one_tab = true
config.tab_bar_at_bottom = true

-- cursor
config.default_cursor_style = 'SteadyBar'
config.cursor_thickness = '3px'

-- disable wayland on Linux
if is_linux() then
  config.enable_wayland = false
end

return config
